int input_oper(int* size);
void clear_and_stop_console();
void menu();
char* string_memory(char* str);
char* string_input(char* str);
char* string_output(char* str);
char* string_memory_realloc(char* str);
char* get_string(int* len);
char* down_first(char* str, int len);
int input_num(int* size);
char* input_new_string(char* s1, char* s2, char* s3, int n1, int n2, int len2);